// ----------------------------------------------------------------------------
// <copyright file="HL7QueryDataEnterer.cs" company="ABC software">
//    Copyright © ABC SOFTWARE. All rights reserved.
//    The source code or its parts to use, reproduce, transfer, copy or
//    keep in an electronic form only from written agreement ABC SOFTWARE.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  acknowledgementDetail.cs
//  Implementation of the Class acknowledgementDetail
//  Generated by Enterprise Architect
//  Created on:      17-okt-2011 19:07:24
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    using System;
    using System.Diagnostics.Contracts;

    /// <summary>
    /// HL7 schemas class
    /// </summary>
    public class HL7QueryDataEnterer : HL7QueryDevice
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryDataEnterer"/> class.
        /// </summary>
        /// <param name="valueData">The value data.</param>
        /// <param name="semanticsText">The semantics text.</param>
        public HL7QueryDataEnterer(HL7II valueData, string semanticsText)
            : base(valueData, semanticsText)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryDataEnterer"/> class.
        /// </summary>
        /// <param name="data">The data.</param>
        public HL7QueryDataEnterer(HL7QueryDevice data)
            : base(data.Value, data.SemanticsText)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryDataEnterer"/> class.
        /// </summary>
        protected HL7QueryDataEnterer()
        {
        }

        /// <summary>
        /// Gets or sets the value data.
        /// </summary>
        /// <value>
        /// The value data.
        /// </value>
        public HL7II ValueData
        {
            get
            {
                return (HL7II)this.Value;
            }

            set
            {
                this.Value = value;
            }
        }
    }
}