// ----------------------------------------------------------------------------
// <copyright file="HL7QuerySortControl.cs" company="ABC software">
//    Copyright © ABC SOFTWARE. All rights reserved.
//    The source code or its parts to use, reproduce, transfer, copy or
//    keep in an electronic form only from written agreement ABC SOFTWARE.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  acknowledgementDetail.cs
//  Implementation of the Class acknowledgementDetail
//  Generated by Enterprise Architect
//  Created on:      17-okt-2011 19:07:24
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    using System;
    using System.Diagnostics.Contracts;

    /// <summary>
    /// HL7 schemas class
    /// </summary>
    public class HL7QuerySortControl
    {
        private int? sequenceNumber;
        private string elementName;
        private HL7ClassificatorId directionCode;

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QuerySortControl"/> class.
        /// </summary>
        /// <param name="sequenceNumber">The sequence number.</param>
        /// <param name="elementName">Name of the element.</param>
        /// <param name="directionCode">The direction code.</param>
        public HL7QuerySortControl(int? sequenceNumber, string elementName, HL7ClassificatorId directionCode)
        {
            SequenceNumber = this.sequenceNumber;
            ElementName = this.elementName;
            DirectionCode = this.directionCode;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QuerySortControl"/> class.
        /// </summary>
        protected HL7QuerySortControl()
        {
        }

        /// <summary>
        /// Gets or sets the sequence number.
        /// </summary>
        /// <value>
        /// The sequence number.
        /// </value>
        public int? SequenceNumber
        {
            get
            {
                return this.sequenceNumber;
            }

            set
            {
                this.sequenceNumber = value;
            }
        }

        /// <summary>
        /// Gets or sets the name of the element.
        /// </summary>
        /// <value>
        /// The name of the element.
        /// </value>
        public string ElementName
        {
            get
            {
                return this.elementName;
            }

            set
            {
                this.elementName = value;
            }
        }

        /// <summary>
        /// Gets or sets the direction code.
        /// </summary>
        /// <value>
        /// The direction code.
        /// </value>
        public HL7ClassificatorId DirectionCode
        {
            get
            {
                return this.directionCode;
            }

            set
            {
                this.directionCode = value;
            }
        }
    }
}