// ----------------------------------------------------------------------------
// <copyright file="HL7QueryByParameterPayload_.cs" company="ABC software">
//    Copyright © ABC SOFTWARE. All rights reserved.
//    The source code or its parts to use, reproduce, transfer, copy or
//    keep in an electronic form only from written agreement ABC SOFTWARE.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  acknowledgementDetail.cs
//  Implementation of the Class acknowledgementDetail
//  Generated by Enterprise Architect
//  Created on:      17-okt-2011 19:07:24
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    using System;
    using System.Diagnostics.Contracts;

    /// <summary>
    /// HL7 schemas class
    /// </summary>
    public class HL7QueryByParameterPayload_
    {
        private HL7II queryId;
        private HL7StatusCode statusCode;
        private HL7ModifyCode modifyCode;
        private HL7ResponseModalityCode responseModalityCode;
        private int? initialQuantity;
        private HL7QuerySenderDevice senderDevice;
        private HL7QueryReceiverDevice receiverDevice;
        private HL7QueryDataEnterer dataEnterer;
        private HL7QueryEventTimeframe queryEventTimeframe;
        private HL7QueryPatientId patientId;
        private HL7QueryResponsibleOrganization responsibleOrganization;
        private HL7QuerySortControl sortControl;

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryByParameterPayload_"/> class.
        /// </summary>
        /// <param name="statusCode">The status code.</param>
        /// <param name="patientId">The patient id.</param>
        public HL7QueryByParameterPayload_(HL7StatusCode statusCode, HL7QueryPatientId patientId)
        {
            StatusCode = statusCode;
            PatientId = patientId;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryByParameterPayload_"/> class.
        /// </summary>
        /// <param name="statusCode">The status code.</param>
        /// <param name="patientId">The patient id.</param>
        public HL7QueryByParameterPayload_(Abc.ServiceModel.Protocol.HL7.HL7StatusCode.HL7StatusCodes statusCode, HL7QueryPatientId patientId)
            : this(new HL7StatusCode(statusCode), patientId)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryByParameterPayload_"/> class.
        /// </summary>
        /// <param name="statusCode">The status code.</param>
        /// <param name="patientIdRootID">The patient id root ID.</param>
        /// <param name="patientIdExtension">The patient id extension.</param>
        /// <param name="patientIdSemanticText">The patient id semantic text.</param>
        public HL7QueryByParameterPayload_(Abc.ServiceModel.Protocol.HL7.HL7StatusCode.HL7StatusCodes statusCode, OId patientIdRootID, string patientIdExtension, string patientIdSemanticText)
            : this(new HL7StatusCode(statusCode), new HL7QueryPatientId(new HL7II(patientIdRootID, patientIdExtension), patientIdSemanticText))
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryByParameterPayload_"/> class.
        /// </summary>
        /// <param name="queryId">The query id.</param>
        /// <param name="statusCode">The status code.</param>
        /// <param name="modifyCode">The modify code.</param>
        /// <param name="responseModalityCode">The response modality code.</param>
        /// <param name="initialQuantity">The initial quantity.</param>
        /// <param name="senderDevice">The sender device.</param>
        /// <param name="receiverDevice">The receiver device.</param>
        /// <param name="dataEnterer">The data enterer.</param>
        /// <param name="queryEventTimeframe">The query event timeframe.</param>
        /// <param name="patientId">The patient id.</param>
        /// <param name="responsibleOrganization">The responsible organization.</param>
        /// <param name="sortControl">The sort control.</param>
        public HL7QueryByParameterPayload_(HL7II queryId, Abc.ServiceModel.Protocol.HL7.HL7StatusCode.HL7StatusCodes statusCode, Abc.ServiceModel.Protocol.HL7.HL7ModifyCode.HL7ModifyCodes modifyCode, Abc.ServiceModel.Protocol.HL7.HL7ResponseModalityCode.HL7ResponseModalityCodes responseModalityCode, int? initialQuantity, HL7QuerySenderDevice senderDevice, HL7QueryReceiverDevice receiverDevice, HL7QueryDataEnterer dataEnterer, HL7QueryEventTimeframe queryEventTimeframe, HL7QueryPatientId patientId, HL7QueryResponsibleOrganization responsibleOrganization, HL7QuerySortControl sortControl)
            : this(queryId, new HL7StatusCode(statusCode), new HL7ModifyCode(modifyCode), new HL7ResponseModalityCode(responseModalityCode), initialQuantity, senderDevice, receiverDevice, dataEnterer, queryEventTimeframe, patientId, responsibleOrganization, sortControl)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryByParameterPayload_"/> class.
        /// </summary>
        /// <param name="queryId">The query id.</param>
        /// <param name="statusCode">The status code.</param>
        /// <param name="modifyCode">The modify code.</param>
        /// <param name="responseModalityCode">The response modality code.</param>
        /// <param name="initialQuantity">The initial quantity.</param>
        /// <param name="senderDevice">The sender device.</param>
        /// <param name="receiverDevice">The receiver device.</param>
        /// <param name="dataEnterer">The data enterer.</param>
        /// <param name="queryEventTimeframe">The query event timeframe.</param>
        /// <param name="patientId">The patient id.</param>
        /// <param name="responsibleOrganization">The responsible organization.</param>
        /// <param name="sortControl">The sort control.</param>
        public HL7QueryByParameterPayload_(HL7II queryId, HL7StatusCode statusCode, HL7ModifyCode modifyCode, HL7ResponseModalityCode responseModalityCode, int? initialQuantity, HL7QuerySenderDevice senderDevice, HL7QueryReceiverDevice receiverDevice, HL7QueryDataEnterer dataEnterer, HL7QueryEventTimeframe queryEventTimeframe, HL7QueryPatientId patientId, HL7QueryResponsibleOrganization responsibleOrganization, HL7QuerySortControl sortControl)
        {
            QueryId = queryId;
            StatusCode = statusCode;
            PatientId = patientId;
            ModifyCode = modifyCode;
            ResponseModalityCode = responseModalityCode;
            InitialQuantity = initialQuantity;
            SenderDevice = senderDevice;
            ReceiverDevice = receiverDevice;
            DataEnterer = dataEnterer;
            QueryEventTimeframe = queryEventTimeframe;
            ResponsibleOrganization = responsibleOrganization;
            SortControl = sortControl;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryByParameterPayload_"/> class.
        /// </summary>
        protected HL7QueryByParameterPayload_()
        {
        }

        /// <summary>
        /// Gets or sets the query id.
        /// </summary>
        /// <value>
        /// The query id.
        /// </value>
        public HL7II QueryId
        {
            get
            {
                return this.queryId;
            }

            set
            {
                this.queryId = value;
            }
        }

        /// <summary>
        /// Gets or sets the sort control.
        /// </summary>
        /// <value>
        /// The sort control.
        /// </value>
        public HL7QuerySortControl SortControl
        {
            get
            {
                return this.sortControl;
            }

            set
            {
                this.sortControl = value;
            }
        }

        /// <summary>
        /// Gets or sets the responsible organization.
        /// </summary>
        /// <value>
        /// The responsible organization.
        /// </value>
        public HL7QueryResponsibleOrganization ResponsibleOrganization
        {
            get
            {
                return this.responsibleOrganization;
            }

            set
            {
                this.responsibleOrganization = value;
            }
        }

        /// <summary>
        /// Gets or sets the query event timeframe.
        /// </summary>
        /// <value>
        /// The query event timeframe.
        /// </value>
        public HL7QueryEventTimeframe QueryEventTimeframe
        {
            get
            {
                return this.queryEventTimeframe;
            }

            set
            {
                this.queryEventTimeframe = value;
            }
        }

        /// <summary>
        /// Gets or sets the data enterer.
        /// </summary>
        /// <value>
        /// The data enterer.
        /// </value>
        public HL7QueryDataEnterer DataEnterer
        {
            get
            {
                return this.dataEnterer;
            }

            set
            {
                this.dataEnterer = value;
            }
        }

        /// <summary>
        /// Gets or sets the receiver device.
        /// </summary>
        /// <value>
        /// The receiver device.
        /// </value>
        public HL7QueryReceiverDevice ReceiverDevice
        {
            get
            {
                return this.receiverDevice;
            }

            set
            {
                this.receiverDevice = value;
            }
        }

        /// <summary>
        /// Gets or sets the sender device.
        /// </summary>
        /// <value>
        /// The sender device.
        /// </value>
        public HL7QuerySenderDevice SenderDevice
        {
            get
            {
                return this.senderDevice;
            }

            set
            {
                this.senderDevice = value;
            }
        }

        /// <summary>
        /// Gets or sets the initial quantity.
        /// </summary>
        /// <value>
        /// The initial quantity.
        /// </value>
        public int? InitialQuantity
        {
            get
            {
                return this.initialQuantity;
            }

            set
            {
                this.initialQuantity = value;
            }
        }

        /// <summary>
        /// Gets or sets the response modality code.
        /// </summary>
        /// <value>
        /// The response modality code.
        /// </value>
        public HL7ResponseModalityCode ResponseModalityCode
        {
            get
            {
                return this.responseModalityCode;
            }

            set
            {
                this.responseModalityCode = value;
            }
        }

        /// <summary>
        /// Gets or sets the modify code.
        /// </summary>
        /// <value>
        /// The modify code.
        /// </value>
        public Abc.ServiceModel.Protocol.HL7.HL7ModifyCode ModifyCode
        {
            get
            {
                return this.modifyCode;
            }

            set
            {
                this.modifyCode = value;
            }
        }

        /// <summary>
        /// Gets or sets the status code.
        /// </summary>
        /// <value>
        /// The status code.
        /// </value>
        public HL7StatusCode StatusCode
        {
            get
            {
                return this.statusCode;
            }

            set
            {
                this.statusCode = value;
            }
        }

        /// <summary>
        /// Gets or sets the patient id.
        /// </summary>
        /// <value>
        /// The patient id.
        /// </value>
        public HL7QueryPatientId PatientId
        {
            get
            {
                return this.patientId;
            }

            set
            {
                this.patientId = value;
            }
        }
    }
}