// ----------------------------------------------------------------------------
// <copyright file="HL7QueryControlAcknowledgement.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  QueryControlAct .cs
//  Implementation of the Class QueryControlAct
//  Generated by Enterprise Architect
//  Created on:      17-okt-2011 19:03:57
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// HL7 shçmas klase.  Vadîbas darbîbas (ControlAct) ar biznesa informâciju.
    /// </summary>
    public class HL7QueryControlAcknowledgement : HL7MessageControlAct
    {
        private HL7QueryAcknowledgement queryAcknowledgement;
        private HL7QueryByParameterPayload queryByParameterPayload;
        private HL7QueryContinuation queryContinuation;

        // public HL7QueryControlAcknowledgement(string code, string text, string priorityCode, string actionCode, string reasonCode, string languageCode, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
        //    : this(code, text, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, subject, queryAcknowledgement)
        // {
        // }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="queryAcknowledgement">The query ack.</param>
        public HL7QueryControlAcknowledgement(string actionCode, string reasonCode, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
            : this(null, null, null, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, null, subject, queryAcknowledgement)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="queryAcknowledgement">The query acknowledgement.</param>
        public HL7QueryControlAcknowledgement(HL7ClassificatorId code, string text, HL7ClassificatorId priorityCode, ICollection<HL7ClassificatorId> reasonCodes, HL7ClassificatorId languageCode, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
            : base(code, text, priorityCode, reasonCodes, languageCode, subject)
        {
            this.QueryAcknowledgement = queryAcknowledgement;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="queryAcknowledgement">The query acknowledgement.</param>
        public HL7QueryControlAcknowledgement(ICollection<HL7ClassificatorId> reasonCodes, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
            : this(null, null, null, reasonCodes, null, subject, queryAcknowledgement)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="queryAcknowledgement">The query ack.</param>
        public HL7QueryControlAcknowledgement(string actionCode, string reasonCode, HL7QueryAcknowledgement queryAcknowledgement)
            : base(new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) })
        {
            this.QueryAcknowledgement = queryAcknowledgement;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="queryAcknowledgement">The query acknowledgement.</param>
        public HL7QueryControlAcknowledgement(ICollection<HL7ClassificatorId> reasonCodes, HL7QueryAcknowledgement queryAcknowledgement)
            : base(reasonCodes)
        {
            this.QueryAcknowledgement = queryAcknowledgement;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="queryByParameterPayload">The query by parameter payload.</param>
        public HL7QueryControlAcknowledgement(string actionCode, string reasonCode, HL7QueryByParameterPayload queryByParameterPayload)
            : base(new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) })
        {
            this.QueryByParameterPayload = queryByParameterPayload;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="queryByParameterPayload">The query by parameter payload.</param>
        public HL7QueryControlAcknowledgement(ICollection<HL7ClassificatorId> reasonCodes, HL7QueryByParameterPayload queryByParameterPayload)
            : base(reasonCodes)
        {
            this.QueryByParameterPayload = queryByParameterPayload;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="queryContinuation">The query continuation.</param>
        public HL7QueryControlAcknowledgement(string actionCode, string reasonCode, HL7QueryContinuation queryContinuation)
            : base(new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) })
        {
            this.QueryContinuation = queryContinuation;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="queryContinuation">The query continuation.</param>
        public HL7QueryControlAcknowledgement(ICollection<HL7ClassificatorId> reasonCodes, HL7QueryContinuation queryContinuation)
            : base(reasonCodes)
        {
            this.QueryContinuation = queryContinuation;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="code">The code. value</param>
        /// <param name="text">The text. value</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="subject">The subject. value</param>
        /// <param name="queryAcknowledgement">The query Acknowledgement.</param>
        public HL7QueryControlAcknowledgement(HL7ClassificatorId code, string text, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
            : this(null, null, null, code, text, priorityCode, actionCode, reasonCode, languageCode, subject, queryAcknowledgement)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryAcknowledgement">The query Acknowledgement.</param>
        public HL7QueryControlAcknowledgement(HL7ClassificatorId code, string text, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7QueryAcknowledgement queryAcknowledgement)
            : this(code, text, priorityCode, actionCode, reasonCode, languageCode, null, queryAcknowledgement)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryAcknowledgement">The query Acknowledgement.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7QueryAcknowledgement queryAcknowledgement)
            : this(dataEnterers, authorOrPerformers, informationRecipients, code, text, priorityCode, actionCode, reasonCode, languageCode, null, queryAcknowledgement)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code. value</param>
        /// <param name="text">The text. value</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="subject">The subject. value</param>
        /// <param name="queryAcknowledgement">The query Acknowledgement.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
            : base(dataEnterers, authorOrPerformers, informationRecipients, code, text, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, subject)
        {
            this.QueryAcknowledgement = queryAcknowledgement;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement" /> class.
        /// </summary>
        /// <param name="overseer">The overseer.</param>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="queryAcknowledgement">The query acknowledgement.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7Overseer> overseer, IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode,  ICollection<HL7ClassificatorId> reasonCodes,  HL7ClassificatorId languageCode, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
            : base(overseer, dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, reasonCodes, languageCode, subject)
        {
            this.QueryAcknowledgement = queryAcknowledgement;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="overseer">The overseer.</param>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="queryAcknowledgement">The query acknowledgement.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7Overseer> overseer, IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
            : base(overseer, dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, subject)
        {
            this.QueryAcknowledgement = queryAcknowledgement;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryAcknowledgement">The query ack.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, ICollection<HL7ClassificatorId> reasonCodes, HL7ClassificatorId languageCode, HL7QueryAcknowledgement queryAcknowledgement)
            : this(dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, reasonCodes, languageCode, null, queryAcknowledgement)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="overseer">The overseer.</param>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryAcknowledgement">The query acknowledgement.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7Overseer> overseer, IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, ICollection<HL7ClassificatorId> reasonCodes, HL7ClassificatorId languageCode, HL7QueryAcknowledgement queryAcknowledgement)
            : this(overseer, dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, reasonCodes, languageCode, null, queryAcknowledgement)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryAcknowledgement">The query acknowledgement.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7QueryAcknowledgement queryAcknowledgement)
            : this(dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, null, queryAcknowledgement)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code. value</param>
        /// <param name="text">The text. value</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCodes">The reason codes.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="subject">The subject. value</param>
        /// <param name="queryAcknowledgement">The query ack.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, ICollection<HL7ClassificatorId> reasonCodes, HL7ClassificatorId languageCode, HL7Subject subject, HL7QueryAcknowledgement queryAcknowledgement)
            : base(dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, reasonCodes, languageCode, subject)
        {
            this.QueryAcknowledgement = queryAcknowledgement;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryByParameterPayload">The query by parameter payload.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7QueryByParameterPayload queryByParameterPayload)
            : base(dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, null)
        {
            this.QueryByParameterPayload = queryByParameterPayload;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="overseer">The overseer.</param>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryByParameterPayload">The query by parameter payload.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7Overseer> overseer, IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7QueryByParameterPayload queryByParameterPayload)
            : base(overseer, dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, null)
        {
            this.QueryByParameterPayload = queryByParameterPayload;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="overseer">The overseer.</param>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryAcknowledgement">The query acknowledgement.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7Overseer> overseer, IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7QueryAcknowledgement queryAcknowledgement)
            : base(overseer, dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, null)
        {
            this.QueryAcknowledgement = queryAcknowledgement;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryByParameterPayload">The query by parameter payload.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, ICollection<HL7ClassificatorId> reasonCode, HL7ClassificatorId languageCode, HL7QueryByParameterPayload queryByParameterPayload)
            : base(dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, reasonCode, languageCode, null)
        {
            this.QueryByParameterPayload = queryByParameterPayload;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="overseer">The overseer.</param>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryByParameterPayload">The query by parameter payload.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7Overseer> overseer, IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, ICollection<HL7ClassificatorId> reasonCode, HL7ClassificatorId languageCode, HL7QueryByParameterPayload queryByParameterPayload)
            : base(overseer, dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, reasonCode, languageCode, null)
        {
            this.QueryByParameterPayload = queryByParameterPayload;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryContinuation">The query continuation.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7QueryContinuation queryContinuation)
            : this(dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, queryContinuation)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="overseer">The overseer.</param>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="actionCode">The action code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryContinuation">The query continuation.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7Overseer> overseer, IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, string actionCode, string reasonCode, HL7ClassificatorId languageCode, HL7QueryContinuation queryContinuation)
            : this(overseer, dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, new HL7ClassificatorId[] { new HL7ClassificatorId(actionCode, HL7Constants.OIds.ActionCodeId), new HL7ClassificatorId(reasonCode, HL7Constants.OIds.ReasonCodeId) }, languageCode, queryContinuation)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryContinuation">The query continuation.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, ICollection<HL7ClassificatorId> reasonCode, HL7ClassificatorId languageCode, HL7QueryContinuation queryContinuation)
            : base(dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, reasonCode, languageCode, null)
        {
            this.queryContinuation = queryContinuation;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        /// </summary>
        /// <param name="overseer">The overseer.</param>
        /// <param name="dataEnterers">The data enterers.</param>
        /// <param name="authorOrPerformers">The author or performers.</param>
        /// <param name="informationRecipients">The information recipients.</param>
        /// <param name="code">The code.</param>
        /// <param name="text">The text.</param>
        /// <param name="effectiveTime">The effective time.</param>
        /// <param name="priorityCode">The priority code.</param>
        /// <param name="reasonCode">The reason code.</param>
        /// <param name="languageCode">The language code.</param>
        /// <param name="queryContinuation">The query continuation.</param>
        public HL7QueryControlAcknowledgement(IEnumerable<HL7Overseer> overseer, IEnumerable<HL7DataEnterer> dataEnterers, IEnumerable<HL7AuthorOrPerformer> authorOrPerformers, ICollection<HL7InformationRecipient> informationRecipients, HL7ClassificatorId code, string text, DateTime? effectiveTime, HL7ClassificatorId priorityCode, ICollection<HL7ClassificatorId> reasonCode, HL7ClassificatorId languageCode, HL7QueryContinuation queryContinuation)
            : base(overseer, dataEnterers, authorOrPerformers, informationRecipients, code, text, effectiveTime, priorityCode, reasonCode, languageCode, null)
        {
            this.queryContinuation = queryContinuation;
        }

        ///// <summary>
        ///// Initializes a new instance of the <see cref="HL7QueryControlAcknowledgement"/> class.
        ///// </summary>
        // protected HL7QueryControlAcknowledgement()
        // {
        // }

        /// <summary>
        /// Gets or sets the query ack. - HL7 shçmas klase.  Vaicâjuma atbildes vadîbas darbîbas prasa tikai vienu obligâto atribûtu (queryAck.queryId), lai identificçtu vaicâjuma sesiju, ar kuru vaicâjuma atbildes ziòojums ir saistîts. Parametru definîciju struktûra ir specifiska katram izmantoðanas gadîjumam.
        /// </summary>
        /// <value>
        /// The query ack.
        /// </value>
        public HL7QueryAcknowledgement QueryAcknowledgement
        {
            get
            {
                return this.queryAcknowledgement;
            }

            set
            {
                // Contract.Requires<ArgumentNullException>(value != null, "value");
                this.queryAcknowledgement = value;
            }
        }

        /// <summary>
        /// Gets or sets the query by parameter payload.
        /// </summary>
        /// <value>
        /// The query by parameter payload.
        /// </value>
        public HL7QueryByParameterPayload QueryByParameterPayload
        {
            get
            {
                return this.queryByParameterPayload;
            }

            set
            {
                this.queryByParameterPayload = value;
            }
        }

        /// <summary>
        /// Gets or sets the query continuation.
        /// </summary>
        /// <value>
        /// The query continuation.
        /// </value>
        public HL7QueryContinuation QueryContinuation
        {
            get
            {
                return this.queryContinuation;
            }

            set
            {
                this.queryContinuation = value;
            }
        }
    }
}