//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=2.0.50727.42.
//
namespace Abc.ServiceModel.UnitTests
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://test")]
    [System.Xml.Serialization.XmlRootAttribute("Test", Namespace = "http://test", IsNullable = false)]
    public partial class XsdTestStructure
    {
        private string attrField;
        private string elemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attr
        {
            get
            {
                return this.attrField;
            }
            set
            {
                this.attrField = value;
            }
        }

        /// <remarks/>
        public string Elem
        {
            get
            {
                return this.elemField;
            }
            set
            {
                this.elemField = value;
            }
        }
    }
}