// ----------------------------------------------------------------------------
// <copyright file="HL7AcknowledgementDetailType.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  AcknowacknowledgementDetailType.cs
//  Implementation of the Class AcknowacknowledgementDetailType
//  Generated by Enterprise Architect
//  Created on:      17-okt-2011 19:04:26
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    /// <summary>
    /// HL7 schemas class
    /// </summary>
    public enum HL7AcknowledgementDetailType
    {
        /// <summary>
        /// I Information value
        /// </summary>
        Information,

        /// <summary>
        /// W Warning value
        /// </summary>
        Warning,

        /// <summary>
        /// E Error value
        /// </summary>
        Error,
    }
}