// ----------------------------------------------------------------------------
// <copyright file="HL7Acknowledgement.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  Acknowledgement.cs
//  Implementation of the Class Acknowledgement
//  Generated by Enterprise Architect
//  Created on:      17-okt-2011 19:03:51
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    /// <summary>
    /// HL7 shçmas klase, Acknowledgement klase ietver informâciju par protokola kârtas numuru, papildus informâciju, ko izmanto ziòojuma gaidîðanas protokols, bet, galvenokârt, nosaka (izmantojot TargetMessage (mçría ziòojuma) klasi), kas tas ir par ziòojumu, kuram ðis ir apstiprinâjums.
    /// </summary>
    public class HL7Acknowledgement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Acknowledgement"/> class.
        /// </summary>
        /// <param name="acknowledgementType">Type of the acknowledgement.</param>
        public HL7Acknowledgement(HL7AcknowledgementType acknowledgementType)
            : this(new HL7IdentificationId(), acknowledgementType, null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Acknowledgement"/> class.
        /// </summary>
        /// <param name="interactionId">The interaction id.</param>
        /// <param name="acknowledgementType">Type of the acknowledgement.</param>
        public HL7Acknowledgement(HL7IdentificationId interactionId, HL7AcknowledgementType acknowledgementType)
            : this(interactionId, acknowledgementType, null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Acknowledgement"/> class.
        /// </summary>
        /// <param name="acknowledgementType">Type of the acknowledgement.</param>
        /// <param name="acknowledgementDetails">The acknowledgement details.</param>
        public HL7Acknowledgement(HL7AcknowledgementType acknowledgementType, IEnumerable<HL7AcknowledgementDetail> acknowledgementDetails)
            : this(new HL7IdentificationId(), acknowledgementType, acknowledgementDetails)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Acknowledgement"/> class.
        /// </summary>
        /// <param name="messageId">The message id.</param>
        /// <param name="acknowledgementType">Type of the acknowledgement.</param>
        /// <param name="acknowledgementDetails">The acknowledgement details.</param>
        public HL7Acknowledgement(Guid messageId, HL7AcknowledgementType acknowledgementType, IEnumerable<HL7AcknowledgementDetail> acknowledgementDetails)
            : this((HL7IdentificationId)new HL7IdentificationId(HL7Constants.OIds.IdentificationId, messageId), acknowledgementType, acknowledgementDetails)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Acknowledgement"/> class.
        /// </summary>
        /// <param name="interactionId">The interaction id.</param>
        /// <param name="acknowledgementType">Type of the acknowledgement.</param>
        /// <param name="acknowledgementDetails">The acknowledgement details.</param>
        public HL7Acknowledgement(HL7IdentificationId interactionId, HL7AcknowledgementType acknowledgementType, IEnumerable<HL7AcknowledgementDetail> acknowledgementDetails)
        {
            this.TargetMessage = interactionId;
            this.AcknowledgementDataType = acknowledgementType;
            this.AcknowledgementDetails = new Collection<HL7AcknowledgementDetail>();

            if (acknowledgementDetails != null)
            {
                foreach (var item in acknowledgementDetails)
                {
                    if (item != null)
                    {
                        this.AcknowledgementDetails.Add(item);
                    }
                }
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Acknowledgement"/> class.
        /// </summary>
        protected HL7Acknowledgement()
        {
        }

        /// <summary>
        /// Gets or sets the type of the acknowledgement data.
        /// </summary>
        /// <value>
        /// The type of the acknowledgement data.
        /// </value>
        public HL7AcknowledgementType AcknowledgementDataType { get; set; }

        /// <summary>
        /// Gets the acknowledgement details.
        /// </summary>
        /// <value>
        /// The acknowledgement details.
        /// </value>
        public ICollection<HL7AcknowledgementDetail> AcknowledgementDetails { get; private set; }

        /// <summary>
        /// Gets or sets the target message.
        /// </summary>
        /// <value>
        /// The target message.
        /// </value>
        public HL7IdentificationId TargetMessage { get; set; }
    }
}