// ----------------------------------------------------------------------------
// <copyright file="HL7ModifyCode.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  HL7Id.cs
//  Implementation of the Class HL7Id
//  Generated by Enterprise Architect
//  Created on:      18-okt-2011 11:58:56
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    /// <summary>
    /// HL7 shçmas klase. Norâda vai vaicâjums ir jauns vai bijis modificçts, definç ðâdas vçrtîbas: M (modificçta) – modificçts vaicâjums  N (jauna) – jauns vaicâjums
    /// </summary>
    public class HL7ModifyCode
    {
        private HL7ModifyCodes code;

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7ModifyCode"/> class.
        /// </summary>
        /// <param name="code">The code.</param>
        public HL7ModifyCode(HL7ModifyCodes code)
        {
            this.code = code;
        }

        /// <summary>
        /// A code specifying the state of the Query.
        /// </summary>
        public enum HL7ModifyCodes
        {
            /// <summary>
            /// Modified subscription to a query server. N (jauna) – jauns vaicâjums
            /// </summary>
            NewSubscription,

            /// <summary>
            /// New subscription to a query server.  M (modificçta) – modificçts vaicâjums
            /// </summary>
            ModifiedSubscription,
        }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>
        /// The extension.
        /// </value>
        public virtual HL7ModifyCodes Code
        {
            get
            {
                return this.code;
            }

            set
            {
                // regex
                this.code = value;
            }
        }

        /// <summary>
        /// Returns a <see cref="string"/> that represents this instance.
        /// </summary>
        /// <returns>
        /// A <see cref="string"/> that represents this instance.
        /// </returns>
        public override string ToString()
        {
            return this.code.ToString();
        }
    }
}