// ----------------------------------------------------------------------------
// <copyright file="HL7Overseer.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  AuthorOrPerformers.cs
//  Implementation of the Class AuthorOrPerformers
//  Generated by Enterprise Architect
//  Created on:      17-okt-2011 19:07:24
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    using System;

    /// <summary>
    /// Vadîbas darbîbâ var bût iesaistîtas vairâkas puses kâ tâs autori (author) vai
    /// izpildîtâji (performer).
    /// Darbîbas autors (author) ir persona, kas nes atbildîbu par tâs iniciâciju
    /// (izveidoðanu). Tas var bût ârsts, kas pasûta testu vai sabiedriskâs veselîbas
    /// darbinieks, kas izlemj informçt vietçjo, valsts vai nacionâlo veselîbas
    /// aizsardzîbas institûciju.
    /// Darbîbas izpildîtâjs (performer) ir persona, kas, galvenokârt, izpilda vadîbas
    /// darbîbu. Gadîjumi, kad tiek izmantots izpildîtâjs (performer) ir reti.
    /// Tieði iesaistîtais ir persona vai ierîce, dati par to ir norâdîti
    /// AssignedPerson vai AssignedDevice CMET. Ir jâòem vçrâ, ka bieþi darbîbas
    /// iniciatore vai izpildîtâja ir organizâcija nevis persona. Arî ðâdâ gadîjumâ ir
    /// jâizmanto AssignedPerson CMET, kas nodroðina organizâcijas, kâ izpildîtâja
    /// lomas reìistrçðanu.
    /// </summary>
    public class HL7Overseer
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Overseer" /> class.
        /// </summary>
        /// <param name="time">The time.</param>
        /// <param name="signatureCode">The signature code.</param>
        /// <param name="signatureText">The signature text.</param>
        /// <param name="assignedPerson">The assigned person.</param>
        public HL7Overseer(DateTime? time, string signatureCode, string signatureText, HL7AssignedPerson assignedPerson)
        {
            if (time.HasValue)
            {
                this.Time = time.Value;
            }

            this.SignatureCode = signatureCode;
            this.SignatureText = signatureText;
            this.AssignedPerson = assignedPerson;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Overseer"/> class.
        /// </summary>
        /// <param name="signatureCode">The signature code.</param>
        /// <param name="signatureText">The signature text.</param>
        /// <param name="assignedPerson">The assigned person.</param>
        public HL7Overseer(string signatureCode, string signatureText, HL7AssignedPerson assignedPerson)
            : this(null, signatureCode, signatureText, assignedPerson)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7Overseer"/> class.
        /// </summary>
        /// <param name="signatureText">The signature text.</param>
        /// <param name="assignedPerson">The assigned person.</param>
        public HL7Overseer(string signatureText, HL7AssignedPerson assignedPerson)
            : this(null, null, signatureText, assignedPerson)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7AuthorOrPerformer"/> class.
        /// </summary>
        /// <param name="assignedPerson">The assigned person.</param>
        public HL7Overseer(HL7AssignedPerson assignedPerson)
            : this(null, null, null, assignedPerson)
        {
        }

        /// <summary>
        /// Gets or sets the assigned person.
        /// </summary>
        /// <value>
        /// The assigned person.
        /// </value>
        public HL7AssignedPerson AssignedPerson { get; set; }

        /// <summary>
        /// Gets or sets the signature code.
        /// </summary>
        /// <value>
        /// The signature code.
        /// </value>
        public string SignatureCode { get; set; }

        /// <summary>
        /// Gets or sets the signature text.
        /// </summary>
        /// <value>
        /// The signature text.
        /// </value>
        public string SignatureText { get; set; }

        /// <summary>
        /// Gets or sets the time.
        /// </summary>
        /// <value>
        /// The time. value
        /// </value>
        public DateTime Time { get; set; }
    }
}