// ----------------------------------------------------------------------------
// <copyright file="HL7PersonId.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  TemplateId.cs
//  Implementation of the Class TemplateId
//  Generated by Enterprise Architect
//  Created on:      18-okt-2011 11:59:46
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    /// <summary>
    /// HL7 shçmas klase.  Personas Identifikators.
    /// </summary>
    public class HL7PersonId : HL7II
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HL7PersonId"/> class.
        /// </summary>
        /// <param name="personCode">The person code.</param>
        public HL7PersonId(string personCode)
            : this(HL7Constants.OIds.PersonCodeOId, personCode)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7PersonId"/> class.
        /// </summary>
        /// <param name="root">The root. value</param>
        /// <param name="extension">The extension.</param>
        public HL7PersonId(OId root, string extension)
            : base(root, extension)
        {
            // root != HL7Constants.Oids.PersonCodeOid
            // regex personCode
        }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>
        /// The extension.
        /// </value>
        public override string Extension
        {
            get
            {
                return base.Extension;
            }

            set
            {
                // regex personCode
                base.Extension = value;
            }
        }
    }
}