// ----------------------------------------------------------------------------
// <copyright file="HL7QueryResponseCode.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  HL7Id.cs
//  Implementation of the Class HL7Id
//  Generated by Enterprise Architect
//  Created on:      18-okt-2011 11:58:56
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    /// <summary>
    /// HL7 shçmas klase. Atribûts dot iespçju sistçmai atgriezt precîzu atbildes statusu (vçrtîbas, kas definçtas domçnâ QueryStatus)
    /// </summary>
    public class HL7QueryResponseCode
    {
        private HL7QueryResponseCodes code;

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryResponseCode"/> class.
        /// </summary>
        /// <param name="code">The code.</param>
        public HL7QueryResponseCode(HL7QueryResponseCodes code)
        {
            this.code = code;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7QueryResponseCode"/> class.
        /// </summary>
        protected HL7QueryResponseCode()
        {
        }

        /// <summary>
        /// A code specifying the state of the Query.
        /// </summary>
        public enum HL7QueryResponseCodes
        {
            /// <summary>
            /// Query Error. Application Error. AE (Aplikâciju kïûda)
            /// </summary>
            ApplicationError,

            /// <summary>
            /// No errors, but no data was found matching the query request specification. NF (Nav kïûdu bet atrasts pieprasîjums, kurð sakrît ar specifikâciju
            /// </summary>
            NoDataFound,

            /// <summary>
            /// Query reponse data found for 1 or more result sets matching the query request specification. OK (Atbildei ir atrasts rezultâts ar vienu vai vairâk pieprasîjumam atbilstoðam datiem)
            /// </summary>
            DataFound,

            /// <summary>
            /// QueryError. Problem with input ParmetersError QE (Problçma ar ieejas parametru)
            /// </summary>
            QueryParameterError
        }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>
        /// The extension.
        /// </value>
        public virtual HL7QueryResponseCodes Code
        {
            get
            {
                return this.code;
            }

            set
            {
                // regex
                this.code = value;
            }
        }

        /// <summary>
        /// Returns a <see cref="string"/> that represents this instance.
        /// </summary>
        /// <returns>
        /// A <see cref="string"/> that represents this instance.
        /// </returns>
        public override string ToString()
        {
            return this.code.ToString();
        }
    }
}