// ----------------------------------------------------------------------------
// <copyright file="HL7StatusCode.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  HL7Id.cs
//  Implementation of the Class HL7Id
//  Generated by Enterprise Architect
//  Created on:      18-okt-2011 11:58:56
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    /// <summary>
    /// HL7 shçmas klase. Definçts ar QueryEventStatus domçnu, ietver ðâdas vaicâjuma statusa vçrtîbas [3].
    /// </summary>
    public class HL7StatusCode
    {
        private HL7StatusCodes code;

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7StatusCode"/> class.
        /// </summary>
        /// <param name="code">The code.</param>
        public HL7StatusCode(HL7StatusCodes code)
        {
            this.code = code;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7StatusCode"/> class.
        /// </summary>
        protected HL7StatusCode()
        {
        }

        /// <summary>
        /// A code specifying the state of the Query.
        /// </summary>
        public enum HL7StatusCodes
        {
            /// <summary>
            /// aborted – priekðlaicîgi pârtraukts
            /// </summary>
            Aborted,

            /// <summary>
            /// deliveredResponse – piegâdâta atbilde
            /// </summary>
            DeliveredResponse,

            /// <summary>
            /// executing – izpildîts
            /// </summary>
            Executing,

            /// <summary>
            /// waitContinuedQueryResponse – jâgaida  turpinâjums
            /// </summary>
            WaitContinuedQueryResponse,

            /// <summary>
            /// new – jauns
            /// </summary>
            New
        }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>
        /// The extension.
        /// </value>
        public virtual HL7StatusCodes Code
        {
            get
            {
                return this.code;
            }

            set
            {
                // regex
                this.code = value;
            }
        }
    }
}