// ----------------------------------------------------------------------------
// <copyright file="HL7TransmissionWrapper.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------

///////////////////////////////////////////////////////////
//  TransmissionWrapper.cs
//  Implementation of the Class TransmissionWrapper
//  Generated by Enterprise Architect
//  Created on:      17-okt-2011 19:03:58
//  Original author: Jura
///////////////////////////////////////////////////////////

namespace Abc.ServiceModel.Protocol.HL7
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    /// <summary>
    /// HL7 schemas class
    /// </summary>
    public class HL7TransmissionWrapper
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HL7TransmissionWrapper"/> class.
        /// </summary>
        /// <param name="templateId">The template id.</param>
        /// <param name="identification">The identification.</param>
        /// <param name="version">The version.</param>
        /// <param name="creationTime">The creation time.</param>
        /// <param name="interactionId">The interaction id.</param>
        /// <param name="processingCode">The processing code.</param>
        /// <param name="processingModeCode">The processing mode code.</param>
        /// <param name="acceptAcknowledgementCode">The accept acknowledgement code.</param>
        /// <param name="sender">The sender.</param>
        /// <param name="receiver">The receiver.</param>
        /// <param name="attentionLines">The attention lines.</param>
        /// <param name="acknowledgement">The acknowledgement.</param>
        /// <param name="controlAct">The control act.</param>
        internal HL7TransmissionWrapper(HL7TemplateId templateId, HL7IdentificationId identification, string version, DateTime creationTime, HL7InteractionId interactionId, HL7ProcessingCode processingCode, HL7ProcessingModeCode processingModeCode, HL7AcceptAcknowledgementCode acceptAcknowledgementCode, HL7Device sender, HL7Device receiver, IEnumerable<HL7AttentionLine> attentionLines, HL7Acknowledgement acknowledgement, HL7ControlAct controlAct)
            : this(templateId, identification, version, creationTime, interactionId, processingCode, processingModeCode, acceptAcknowledgementCode, null, sender, receiver, attentionLines, acknowledgement, controlAct)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7TransmissionWrapper"/> class.
        /// </summary>
        /// <param name="templateId">The template id.</param>
        /// <param name="identification">The identification.</param>
        /// <param name="version">The version.</param>
        /// <param name="creationTime">The creation time.</param>
        /// <param name="interactionId">The interaction id.</param>
        /// <param name="processingCode">The processing code.</param>
        /// <param name="processingModeCode">The processing mode code.</param>
        /// <param name="acceptAcknowledgementCode">The accept acknowledgement code.</param>
        /// <param name="sequenceNumber">The sequence number.</param>
        /// <param name="sender">The sender.</param>
        /// <param name="receiver">The receiver.</param>
        /// <param name="attentionLines">The attention lines.</param>
        /// <param name="acknowledgement">The acknowledgement.</param>
        /// <param name="controlAct">The control act.</param>
        internal HL7TransmissionWrapper(HL7TemplateId templateId, HL7IdentificationId identification, string version, DateTime creationTime, HL7InteractionId interactionId, HL7ProcessingCode processingCode, HL7ProcessingModeCode processingModeCode, HL7AcceptAcknowledgementCode acceptAcknowledgementCode, int? sequenceNumber, HL7Device sender, HL7Device receiver, IEnumerable<HL7AttentionLine> attentionLines, HL7Acknowledgement acknowledgement, HL7ControlAct controlAct)
        {
            // SetData(templateId, identification, version, interaction, processingCode, receiverIdentification, senderIdentification, colAtt);
            this.TemplateId = templateId;
            this.IdentificationId = identification;
            this.CreationTime = creationTime;
            this.VersionCode = version;
            this.InteractionId = interactionId;
            this.ProcessingCode = processingCode;
            this.ProcessingModeCode = processingModeCode;
            this.AcceptAcknowledgementCode = acceptAcknowledgementCode;
            this.SequenceNumber = sequenceNumber;
            this.Receiver = receiver;
            this.Sender = sender;

            this.AttentionLineCollection = new Collection<HL7AttentionLine>();

            if (attentionLines != null)
            {
                foreach (var item in attentionLines)
                {
                    if (item != null)
                    {
                        this.AttentionLineCollection.Add(item);
                    }
                }
            }

            this.Acknowledgement = acknowledgement; // TODO: null
            this.ControlAct = controlAct;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HL7TransmissionWrapper"/> class.
        /// </summary>
        protected HL7TransmissionWrapper()
        {
        }

        /// <summary>
        /// Gets or sets the accept acknowledgement code.
        /// </summary>
        /// <value>
        /// The accept acknowledgement code.
        /// </value>
        public HL7AcceptAcknowledgementCode AcceptAcknowledgementCode { get; set; }

        /// <summary>
        /// Gets or sets the acknowledgement.
        /// </summary>
        /// <value>
        /// The acknowledgement.
        /// </value>
        public HL7Acknowledgement Acknowledgement { get; set; }

        /// <summary>
        /// Gets the attention line collection.
        /// </summary>
        public ICollection<HL7AttentionLine> AttentionLineCollection { get; private set; }

        /// <summary>
        /// Gets or sets the control act.
        /// </summary>
        /// <value>
        /// The control act.
        /// </value>
        public HL7ControlAct ControlAct { get; set; }

        /// <summary>
        /// Gets or sets the creation time.
        /// </summary>
        /// <value>
        /// The creation time.
        /// </value>
        public DateTime CreationTime { get; set; }

        /// <summary>
        /// Gets or sets the identification id.
        /// </summary>
        /// <value>
        /// The identification id.
        /// </value>
        public HL7IdentificationId IdentificationId { get; set; }

        /// <summary>
        /// Gets or sets the interaction id.
        /// </summary>
        /// <value>
        /// The interaction id.
        /// </value>
        public HL7InteractionId InteractionId { get; set; }

        /// <summary>
        /// Gets or sets the processing code.
        /// </summary>
        /// <value>
        /// The processing code.
        /// </value>
        public HL7ProcessingCode ProcessingCode { get; set; }

        /// <summary>
        /// Gets or sets the processing mode code.
        /// </summary>
        /// <value>
        /// The processing mode code.
        /// </value>
        public HL7ProcessingModeCode ProcessingModeCode { get; set; }

        /// <summary>
        /// Gets or sets the receiver.
        /// </summary>
        /// <value>
        /// The receiver.
        /// </value>
        public HL7Device Receiver { get; set; }

        /// <summary>
        /// Gets or sets the sender.
        /// </summary>
        /// <value>
        /// The sender.
        /// </value>
        public HL7Device Sender { get; set; }

        /// <summary>
        /// Gets or sets the sequence number.
        /// </summary>
        /// <value>
        /// The sequence number.
        /// </value>
        public int? SequenceNumber { get; set; }

        /// <summary>
        /// Gets or sets the template id.
        /// </summary>
        /// <value>
        /// The template id.
        /// </value>
        public HL7TemplateId TemplateId { get; set; }

        /// <summary>
        /// Gets or sets the version code.
        /// </summary>
        /// <value>
        /// The version code.
        /// </value>
        public string VersionCode { get; set; }
    }
}