//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abc.ServiceModel.Protocol.HL7 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Abc.ServiceModel.Protocol.HL7.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcknowledgementDetail typeCode incorrect (it must be attribute of AcknowledgementDetail (W,E,I)).
        /// </summary>
        internal static string AcknowledgementDetailTypeCode {
            get {
                return ResourceManager.GetString("AcknowledgementDetailTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set AckTypeCode atribute.
        /// </summary>
        internal static string AckTypeCodeAtributeNotSet {
            get {
                return ResourceManager.GetString("AckTypeCodeAtributeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set AckTypeCode element.
        /// </summary>
        internal static string ACkTypeCodeElementNotSet {
            get {
                return ResourceManager.GetString("ACkTypeCodeElementNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be set in request.
        /// </summary>
        internal static string CanNotBeSetReq {
            get {
                return ResourceManager.GetString("CanNotBeSetReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be set in response.
        /// </summary>
        internal static string CanNotBeSetResp {
            get {
                return ResourceManager.GetString("CanNotBeSetResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not full {0}.
        /// </summary>
        internal static string DataNotFull {
            get {
                return ResourceManager.GetString("DataNotFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element must starts with: {0}.
        /// </summary>
        internal static string ElementStart {
            get {
                return ResourceManager.GetString("ElementStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7Acknowledgement contains errors, type {0} is incorrect, it must be (AE or CE).
        /// </summary>
        internal static string ErrorCheck {
            get {
                return ResourceManager.GetString("ErrorCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} date is incorrect for format {1}.
        /// </summary>
        internal static string IncorrectDateTimeFormat {
            get {
                return ResourceManager.GetString("IncorrectDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1} is incorrect.
        /// </summary>
        internal static string IsIncorrect {
            get {
                return ResourceManager.GetString("IsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not: {1}.
        /// </summary>
        internal static string IsNot {
            get {
                return ResourceManager.GetString("IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be set.
        /// </summary>
        internal static string MustBeSet {
            get {
                return ResourceManager.GetString("MustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1} is not Oid.
        /// </summary>
        internal static string NotOid {
            get {
                return ResourceManager.GetString("NotOid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is null or empty.
        /// </summary>
        internal static string NullOrEmptyAtribute {
            get {
                return ResourceManager.GetString("NullOrEmptyAtribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not query response.
        /// </summary>
        internal static string QueryResponse {
            get {
                return ResourceManager.GetString("QueryResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResonCodes is not set.
        /// </summary>
        internal static string ReasonCodesIsNotSet {
            get {
                return ResourceManager.GetString("ReasonCodesIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  in {1} is not {2}.
        /// </summary>
        internal static string ResultIsNot {
            get {
                return ResourceManager.GetString("ResultIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown message type.
        /// </summary>
        internal static string UnknownMessageType {
            get {
                return ResourceManager.GetString("UnknownMessageType", resourceCulture);
            }
        }
    }
}
