//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abc.ServiceModel.HL7 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SrProtocol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SrProtocol() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Abc.ServiceModel.HL7.SrProtocol", typeof(SrProtocol).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action code is not Set.
        /// </summary>
        internal static string ActionCodeIsNotSet {
            get {
                return ResourceManager.GetString("ActionCodeIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 atributes is not set.
        /// </summary>
        internal static string HL7AtributesIsNotSet {
            get {
                return ResourceManager.GetString("HL7AtributesIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect interactionId.
        /// </summary>
        internal static string IncorectInteractionId {
            get {
                return ResourceManager.GetString("IncorectInteractionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplyAction, attribute.ReplyTemplate.
        /// </summary>
        internal static string IncorrectAction {
            get {
                return ResourceManager.GetString("IncorrectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not saveResponse, {0} is not allowed.
        /// </summary>
        internal static string IsNotAllowed {
            get {
                return ResourceManager.GetString("IsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not set.
        /// </summary>
        internal static string IsNotSet {
            get {
                return ResourceManager.GetString("IsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.Context is not set.
        /// </summary>
        internal static string OperationContextIsNotSet {
            get {
                return ResourceManager.GetString("OperationContextIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason code is not Set.
        /// </summary>
        internal static string ResonCodeIsNotSet {
            get {
                return ResourceManager.GetString("ResonCodeIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
